
using System.IO;
using System.Linq;
using pbn.tokens;

namespace manipulators;

/// <summary>
/// Used to execute the --info command.
/// </summary>
class PbnInfoPrinter
{
    public static void PrintOverview(string filename, PbnFile file, TextWriter outStream)
    {
        outStream.WriteLine($"File: {filename}");
        outStream.Write("Boards: ");
        if (file.BoardContexts.Count == 0)
            outStream.WriteLine("None");
        else
        {
            outStream.Write($"{file.BoardContexts[0].BoardNumber} - {file.BoardContexts.Last().BoardNumber} ");
            outStream.WriteLine($"({file.BoardContexts.Count} boards)");
        }

        outStream.WriteLine("Analyses: No");

        var generator = GetGeneratorInfo(file);
        if (!string.IsNullOrEmpty(generator))
            outStream.WriteLine($"Generated by: {generator}");
    }

    public static string GetGeneratorInfo(PbnFile file)
    {
        var token = file.Tokens().FirstOrDefault(t =>
        {
            if (t is Tag tag && tag.Tagname == "Generator")
                return true;
            return false;
        });

        if (token == null)
            return "";

        return (token as Tag)?.Content ?? "";
    }
}